-- Create Users table
CREATE TABLE USERS (
    USER_ID VARCHAR2(36) PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'student',
    CASUAL_LEAVE_BALANCE NUMBER(5) DEFAULT 10,
    MEDICAL_LEAVE_BALANCE NUMBER(5) DEFAULT 10
);

-- Create Leave Applications table
CREATE TABLE LEAVE_APPLICATIONS (
    APPLICATION_ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    LEAVE_TYPE VARCHAR2(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'pending',
    REASON VARCHAR2(500),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create sequence for generating IDs
CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE APPLICATION_ID_SEQ START WITH 1 INCREMENT BY 1; 